"""criando o campo created_at em product

Revision ID: 506264103b48
Revises: 2ca70d9eee44
Create Date: 2021-12-06 17:23:13.525986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506264103b48'
down_revision = '2ca70d9eee44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
