"""drop costumer and address table

Revision ID: 92a4871f04fe
Revises: 3122eb84bea3
Create Date: 2021-12-08 11:12:01.627159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a4871f04fe'
down_revision = '3122eb84bea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=45), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=45), nullable=True),
    sa.Column('cpf_cnpj', sa.VARCHAR(length=45), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=45), nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=6), nullable=True),
    sa.Column('neighbourhood', sa.VARCHAR(length=45), nullable=True),
    sa.Column('primary', sa.BOOLEAN(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
